### ISSUE TITLE
[Feature] Exclude Folders

### ISSUE THREAD

**Issue by Randy-Buchholz** [lsoft/AdjustNamespace#1]
Please add the ability to exclude folders in the hierarchy from the namespace.
Having a visual indicator would be nice too.

Example: Right click folder and have `Adjust Namespace` and `Exclude Folder`. Selecting `Exclude Folder` changes the color of the folder Icon. (My preference would be a light blue color). `Adjust Namespace` would skip these folders when building the namespace.

**Comment by lsoft** [comment]
@Randy-Buchholz could you share a real use case for this? such feature can be implemented in various ways with different complexity, and I want to understand where such thing is useful specifically.

**Comment by Randy-Buchholz** [comment]
A main use is grouping. Say I have a large number of GUI Widgets. I want them available for users in the `Gui.Widgets` namespace.  They have some basic groupings - Buttons, Text, Image, etc.

```
Widgets Folder-
  - Buttons Folder (excluded)
     - W1.cs
     - W2.cs
  - Text Folder (excluded)
     - W3.cs
     - W4.cs
```
 
 If I tag folders Buttons and Text for exclude, they turn blue so I know that "adjust" will produce
WIdgets.W1, not Widgets.Buttons.W1. 

Similar is sub-grouping
```
Folder Outer -
    MainClassifier.cs
    Folder Main Details (ns-exclude)
       IMainClassifier.cs
       ImpMainClassifier.cs
    SecondClassifier.cs
    Folder Second Details (ns-exclude)
       ISecondClassifier.cs
       ImpMainClassifier.cs
 ```
Here I can keep my primary files at a higher level and stash the others below.
It doesn't affect the namespace, but makes it easier to navigate my project files

**Comment by lsoft** [comment]
@Randy-Buchholz let's start from small steps.

I think that's good to store skipped folders in the special file, that can be pushed to git and shared between the whole team.

So, please

1. take the current version of this VSIX from this repository (NOT from a VS marketplace). Compile it and install into your VS.
2. create a file with name `adjust_namespaces_settings.xml` in the folder of your SLN.
3. put the following onto that file (utf8):

```XML
<?xml version="1.0"?>
<AdjustNamespaceSettings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <SkippedFolderSuffixes>
<!--
here is a list of skipped folders
you can add an item with its full path like these:
    <string>C:\projects\github\AdjustNamespace\Tests\Subject\TestProject\A\B\C\</string>
    <string>C:\projects\github\AdjustNamespace\Tests\Subject\TestProject\A\B\C</string>
or you can add only a RELATIVE path from THIS folder like these:
    <string>TestProject\A\B</string>
    <string>TestProject\A\B\</string>
-->
  </SkippedFolderSuffixes>
</AdjustNamespaceSettings>
```

4. Perform the appropriate setup of the file (add skipped folders).
5. Give it a try, and lemme know your feedback.

I'm not sure I want to fight with the custom folder icons (but who knows...), but some custom widow to deal with skipped folders would be useful at the step 2.

Examples you can see into `Tests\Standard` folder.

**Comment by Randy-Buchholz** [comment]
I like the xml file approach and the popup window. 
Some quick feedback:

I did a quick build and install but it's (seemingly) not working correctly.
It's only removes the ProjectName from the front no matter what path I use. 
"C:\Temp\A\B\Class1.cs" with <>\Temp\A\</> produces "namespace A.B" - It should be "namespace Temp.B".

The scan detects folders in matching ns paths for processing. Orphans (not in folder/ns) are not detected. So, a workflow is Sync (built-in), Adjust (yours) to do the whole thing.

This is just some quick FYI - I'll spend some time with this later and give you some better info.

**Comment by lsoft** [comment]
@Randy-Buchholz try to remove a first slash `<>\Temp\A</>` -> `<>Temp\A</>`;

for me `<string>TestProject\A</string>` is working fine, but `<string>\TestProject\A</string>` is not.

**Comment by lsoft** [comment]
@Randy-Buchholz fyi the window has been added in 0.1.14

![image](https://user-images.githubusercontent.com/5988558/204037366-b6a697eb-d2c5-4808-ad91-d83544ae6dcd.png)

**Comment by lsoft** [comment]
Close as completed, as no feedback has come.
