### ISSUE TITLE
Option to use the project's AssemblyName property or some arbitrary namespace instead of its name as the base namespace

### ISSUE THREAD

**Issue by ekolis** [lsoft/AdjustNamespace#10]
A pattern I've used a few times is to create several projects with the same AssemblyName so that they can reference each other without having to create all sorts of nested namespaces within the solution. e.g. a project called FrEee.Core.Utility might just have an assembly name of FrEee like several other projects in the solution. However this doesn't work with this tool because it wants to use the project name, so I get weird namespaces like FrEee.Core.Utility.Utility when I want FrEee.Utility. An option to switch to using the assembly name for the root namespace would be appreciated, or to switch it to an arbitrary namespace of my choosing. Thanks!

**Comment by ekolis** [comment]
Oh, wait, there is a separate Default Namespace setting on the project.

**Comment by lsoft** [comment]
Looks like there is no problem. I'm closing this. Reopen if I'm wrong.
