### ISSUE TITLE
not load extention

### ISSUE THREAD

**Issue by saiid2020** [lsoft/AdjustNamespace#9]
<entry>
    <record>936</record>
    <time>2023/10/08 07:32:38.352</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [AdjustNamespacePackage]</description>
    <guid>{19967834-2536-4A51-82F7-E607434734D2}</guid>
  </entry>
  <entry>
    <record>937</record>
    <time>2023/10/08 07:32:38.469</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [AdjustNamespacePackage]Source: &apos;AdjustNamespace&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Threading, Version=17.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at AdjustNamespace.AdjustNamespacePackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{19967834-2536-4A51-82F7-E607434734D2}</guid>
    <hr>0x80070002</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by lsoft** [comment]
hi @saiid2020!

could you share you VS version? I checked in 17.8 preview 2.0 right now, and do not see any problem here...

**Comment by lsoft** [comment]
@saiid2020 I'm going to close this. Let me know if any additional information appears.
